---
title: "Sucrose_Circadian_ORA"
output: html_document
date: "2024-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#BiocManager::install("clusterProfiler",force= TRUE  )

#install.packages('stringi',configure.args="--disable-pkg-config", method = 'wininet')




library(tidyverse)
library(readxl)
library (dplyr)

library(clusterProfiler)
library(DESeq2)
library(GO.db)
```

## Load Data

```{r, include = FALSE}
# load count data
#counts <- read.csv("homology_TPM_Counts_03_24_2024.csv")

# change row names to gene names
#rownames(counts) = counts$X
# remove X column
#counts <- counts %>% dplyr::select(-c("X"))

# load gene annotations
annotations <- read.csv("ref_protein_coding_7942_test.csv")


```

# COG Enrichment Using Original Annotation File

```{r}
COGs <- annotations %>% 
  dplyr::select(c(locus_tag, COG_category)) %>%
  dplyr::mutate(COG_category = strsplit(COG_category, '')) %>%
  tidyr::unnest(COG_category)

COGs$COG_category <- na_if(COGs$COG_category, "-")

COGs <- COGs[,c(2,1)]


#background_genes <- rownames(counts)
#background_genes <- background_genes[background_genes %in% annotations$locus_tag]

COG_categories <- c('A',"B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q",
                    "S", "T", "U", "V", "Z", 'R' )
COG_descriptions <- c('RNA processing and modification',"Chromatin Structure and dynamics", "Energy production and conversion", "Cell cycle control and mitosis", "Amino Acid metabolis and transport", "Nucleotide metabolism and transport", "Carbohydrate metabolism and transport", "Coenzyme metabolism", "Lipid metabolism", "Translation", "Transcription", "Replication and repair", "Cell wall/membrane/envelop biogenesis", "Cell motility", "Post-translational modification, protein turnover, chaperone functions", "Inorganic ion transport and metabolism", "Secondary Structure", "Function Unknown", "Signal Transduction", "Intracellular trafficing and secretion", "Defense Mechanisms", "Cytoskeleton", 'Dummy')
COGterm2name <- data.frame(COG_categories, COG_descriptions)



```

## KEGG Pathway Enrichment Using Original Annotation File

```{r}

KEGGs <- annotations %>% 
  dplyr::select(c(locus_tag, KEGG_Pathway)) %>%
  dplyr::mutate(KEGG_Pathway = strsplit(KEGG_Pathway, ',')) %>%
  tidyr::unnest(KEGG_Pathway)
KEGGs <- KEGGs[,c(2,1)]
KEGGs <- subset(KEGGs, grepl("^k", KEGGs$KEGG_Pathway))


photosynth<-KEGGs[str_detect(KEGGs$KEGG_Pathway, "ko00195"), ]
oxidative<-KEGGs[str_detect(KEGGs$KEGG_Pathway, "ko00190"), ]




```
## KEGG Module Enrichment Using Original Annotation File

```{r}

KEGGs_mod <- annotations %>% 
  dplyr::select(c(locus_tag, KEGG_Module)) %>%
  dplyr::mutate(KEGG_Module = strsplit(KEGG_Module, ',')) %>%
  tidyr::unnest(KEGG_Module)
KEGGs_mod <- KEGGs_mod[,c(2,1)]



```

#functional enrichment of core genome homologs below
```{r}


# T0
core <- read.csv(file = "grn_1100_min9_enrichment_data.csv", header = T)


```

## COG Enrichment

Up and down-regulated genes.. Separate sections for only up-regulated and down-regulated below. 

```{r}
#A is dummy COG
core_genes <- core$locus_tag

core_COG_results <- enricher(gene = core_genes,
                        TERM2GENE = COGs,
                        TERM2NAME = COGterm2name,
                        pvalueCutoff= 0.05 )
core_COG_df <- as.data.frame(core_COG_results)
core_COG_df


```

## KEGG Enrichment

```{r}
# ko00000 is dummy

core_KEGG_results <- enricher(gene = core_genes,
                         TERM2GENE = KEGGs,
                         pvalueCutoff =0.05, #10e-5 is the consensus
                         #minGSSize =10,
                         #maxGSSize=200
                         )
core_KEGG_df <- as.data.frame(core_KEGG_results)
core_KEGG_df
write.csv(core_KEGG_df, 'core_KEGG_enrichment.csv')
```

```{R}
yy<- enrichKEGG(core$old_locus_tag, organism= 'syf',
                pvalueCutoff=0.3,
                minGSSize = 5,          
                maxGSSize = 400, 
                keyType = "kegg",
                use_internal_data = FALSE) 
head(yy)



```
